import type { ParsedElement } from "../types.js";
import { escapeSingleQuoted } from "./escape.js";

const HEADER = `// AI-managed — fully regenerated by likec4-agent sync on every run.
// Do not hand-edit; your changes will be overwritten on the next sync.`;

export function emitElements(elements: ParsedElement[]): string {
  const sorted = [...elements].sort((a, b) => a.id.localeCompare(b.id));

  const blocks = sorted.map((el) => {
    const lines = [`  ${el.id} = ${el.kind} '${escapeSingleQuoted(el.title)}' {`];
    if (el.technology) {
      lines.push(`    technology '${escapeSingleQuoted(el.technology)}'`);
    }
    if (el.description) {
      lines.push(`    description '${escapeSingleQuoted(el.description)}'`);
    }
    lines.push("  }");
    return lines.join("\n");
  });

  return `${HEADER}\nmodel {\n${blocks.map((b) => `${b}\n`).join("\n")}}\n`;
}
