import type { ParsedRelationship } from "../types.js";
import { escapeDoubleQuoted, escapeSingleQuoted } from "./escape.js";

const HEADER = `// AI-managed — fully regenerated by likec4-agent sync on every run.
// Do not hand-edit; your changes will be overwritten on the next sync.`;

export function emitRelationships(relationships: ParsedRelationship[]): string {
  const sorted = [...relationships].sort((a, b) => {
    return (
      a.source.localeCompare(b.source) ||
      a.target.localeCompare(b.target) ||
      a.label.localeCompare(b.label)
    );
  });

  const lines = sorted.map((rel) => {
    const arrow = rel.kind ? `-[${rel.kind}]->` : "->";
    const tech = rel.technology ? ` '${escapeSingleQuoted(rel.technology)}'` : "";
    return `  ${rel.source} ${arrow} ${rel.target} "${escapeDoubleQuoted(rel.label)}"${tech} // ${rel.sourceFile}:${rel.sourceLine}`;
  });

  return `${HEADER}\nmodel {\n${lines.join("\n")}${lines.length > 0 ? "\n" : ""}}\n`;
}
